Traceback (most recent call last):
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/docs/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/docs/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
box = puw.quantity(2.0*np.identity(3), 'nm')
molsys = msm.build.make_water_box(box)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m box [38;5;241m=[39m puw[38;5;241m.[39mquantity([38;5;241m2.0[39m[38;5;241m*[39mnp[38;5;241m.[39midentity([38;5;241m3[39m), [38;5;124m'[39m[38;5;124mnm[39m[38;5;124m'[39m)
[0;32m----> 2[0m molsys [38;5;241m=[39m [43mmsm[49m[38;5;241;43m.[39;49m[43mbuild[49m[38;5;241;43m.[39;49m[43mmake_water_box[49m[43m([49m[43mbox[49m[43m)[49m

File [0;32m~/micromamba/envs/docs/lib/python3.12/site-packages/molsysmt/_private/digestion/digest.py:122[0m, in [0;36mdigest.<locals>.digestor.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    120[0m     [38;5;28;01mreturn[39;00m func(all_args[[38;5;124m'[39m[38;5;124mself[39m[38;5;124m'[39m], [38;5;241m*[39m[38;5;241m*[39mfinal_args)
[1;32m    121[0m [38;5;28;01melse[39;00m:
[0;32m--> 122[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfinal_args[49m[43m)[49m

File [0;32m~/micromamba/envs/docs/lib/python3.12/site-packages/molsysmt/build/make_water_box.py:28[0m, in [0;36mmake_water_box[0;34m(box, form)[0m
[1;32m     25[0m box [38;5;241m=[39m puw[38;5;241m.[39mget_value(box[[38;5;241m0[39m], to_unit[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnm[39m[38;5;124m'[39m)
[1;32m     26[0m inv_box [38;5;241m=[39m np[38;5;241m.[39mlinalg[38;5;241m.[39minv(box)
[0;32m---> 28[0m aux_item [38;5;241m=[39m to_molsysmt_Structures([43mpath[49m([38;5;124m'[39m[38;5;124mmolsysmt.data.gro[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mspc216.gro[39m[38;5;124m'[39m))
[1;32m     29[0m tile [38;5;241m=[39m puw[38;5;241m.[39mget_value(aux_item[38;5;241m.[39mcoordinates[[38;5;241m0[39m], to_unit[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnm[39m[38;5;124m'[39m)
[1;32m     30[0m length_tile [38;5;241m=[39m [38;5;241m1.86206[39m [38;5;66;03m# nm[39;00m

[0;31mNameError[0m: name 'path' is not defined

